### ISSUE TITLE
Over 100A

### ISSUE THREAD

**Issue by adrusa** [solarsnoop/PCM60X-Monitor#2]
I have a clone of this charge controller made by Felicity. This code works well with it. Thank you for your efforts. However, my Charge Controller is rated 120A, but I noticed that this software appears to read only 100A and the rest is truncated. The CC LCD showed above 100A, but this software can not show it. Thanks.

**Comment by solarsnoop** [comment]
I don`t know this charge controller, but the reason can be that the qpig result is different. You can do the follow steps for find it out:
Write a test code eg:

import time
import urllib
import serial
QCODE = "\x51\x50\x49\x52\x49\xF8\x54\x0D"
ser = serial.Serial(port='/dev/ttyUSB0',baudrate=2400,timeout=2)
print QCODE
ser.write(QCODE)
result = ser.read(70)
print result
ser.close()

than save it as test.py
after call in a comand window 
python2 test.py

you shoud see like this:
QPIRI�T
(3000 24 60.0 14.60 13.85 02 01 +00.0 00 00 2 11.50 0)�

please post it when your charger charge over 100 A maybe i need just modify the code for cases when the current is over 100A

**Comment by adrusa** [comment]
Thank you for taking out time to reply. This is the output.
QPIRI▒T
(3000 48 20.0 13.85 13.85 02 01 +00.0 00 04 4 11.50 0▒


Thanks

**Comment by adrusa** [comment]
On careful look, the code actually just returns the correct value minus 100. So, 117A is returned as 17A.

**Comment by solarsnoop** [comment]
Sorry i made a mistake, I request you the wrong code, but i am wondering your inverter seems to limited by 20A in the settings (?)

How ever i need the result of QPIGS = "\x51\x50\x49\x47\x53\xB7\xA9\x0D":

import time
import urllib
import serial
QCODE = "\x51\x50\x49\x47\x53\xB7\xA9\x0D"
ser = serial.Serial(port='/dev/ttyUSB0',baudrate=2400,timeout=2)
print QCODE
ser.write(QCODE)
result = ser.read(70)
print result
ser.close()

the best would be i get the result when the inverter generate over 100A. From the result i can see is there any flag bit for over 100 or under 100A. So please try again with the code below just change the QCODE please.

**Comment by adrusa** [comment]
This is when the current is 103.58A
QPIGS▒▒
(100.7 55.03 03.58 35.06 34.66 5708 +061 00.12 +070 0000 11000000▒B

And this when the current is 35.61A
QPIGS▒▒
(102.7 54.96 35.61 12.27 11.55 1919 +062 00.19 +070 0000 11000000▒!

Thank you

> Sorry i made a mistake, I request you the wrong code, but i am wondering your inverter seems to limited by 20A in the settings (?)
> 
> How ever i need the result of QPIGS = "\x51\x50\x49\x47\x53\xB7\xA9\x0D":
> 
> import time import urllib import serial QCODE = "\x51\x50\x49\x47\x53\xB7\xA9\x0D" ser = serial.Serial(port='/dev/ttyUSB0',baudrate=2400,timeout=2) print QCODE ser.write(QCODE) result = ser.read(70) print result ser.close()
> 
> the best would be i get the result when the inverter generate over 100A. From the result i can see is there any flag bit for over 100 or under 100A. So please try again with the code below just change the QCODE please.

**Comment by solarsnoop** [comment]
Ok easy :-) you see:
(100.7 55.03 03.58 35.06 34.66 **5708** +061 00.12 +070 0000 11000000▒B
this is the Power and Current is a result from 
(100.7 **55.03** 03.58 35.06 34.66 **5708** +061 00.12 +070 0000 11000000▒B

5708/55.03 = 103,7 (its not exactly but nearly exactly)

The code you need do add is:

` current=result [31:35]/result [41:46]`

you can also use 

`current=result [31:35]//result [41:46]
`
in this case you have an integer: 103 instead of 103.7....

and ignore the current from the result 

I hope you understand what i mean

So if you use the monitor software you go and look for the refresh.php script and go in line 56:

`$current = floatval($einzeln[2]); ### Batt Ampere`

change this code part to:

`$current=$pvwatts/$volt;`

than it should works and show the correct Ampere I will update the script and change it so that it will be show the current as a result of PV Power and Battery Voltage

Would be great you can post a pic or link of your useing controller, thx

**Comment by adrusa** [comment]
Thank you very much. I actually used a function node in node red to accomplish the same thing but I think your suggestion is more elegant. Thank you.
